### ISSUE TITLE
リソース設計を行う

### ISSUE THREAD

**Issue by ot0m1** [ot0m1/Srive#25]
# URI 設計

Method | Path | Discription
-- | -- | --
GET | / | トップページ：サービス概要説明、Spotify へのログインボタンなど
POST | /auth | Spotify へのログイン（Spotify へのログイン画面へのリダイレクト）
DELETE | /auth | Spotify からのログアウト
POST | /search | アーティストを検索
POST | /playlists | 新規プレイリストの追加

`/auth`は秘匿したい情報をパラメータに持つので、POST にしています。

**Comment by ot0m1** [comment]
## DB 設計

 データベースは利用しません。永続化が必要なデータはすべて Spotify 側で持ち、アプリケーション側では必要としません。
Spotify というクラスを作成する予定ですが、コントローラーとしての利用だけでモデルとしては利用しない設計を予定しています。

**Comment by kfukai23** [comment]
> POST | /search/:keyword | アーティストを検索

検索は、以下のどちらかのパターンを良く見ます。
- GET にしつつ、検索キーワードはクエリパラメータの形で渡す
- POST にしつつ、検索キーワードはリクエストボディに入れて渡す

↓あたりも参考にしつつ、どちらかに寄せるとよいと思います〜
https://qiita.com/sakuraya/items/6f1030279a747bcce648#%E5%8B%95%E7%9A%84%E3%81%AA%E3%81%AE%E3%81%AF%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%A7url%E3%81%AF%E5%B8%B8%E3%81%AB%E9%9D%99%E7%9A%84%E3%81%A7%E3%81%82%E3%82%8B


> POST | /playlists/:id | 新規プレイリストの追加

`:id`とは、これから作成されるプレイリストの ID を想定していますか？
もしそうであれば、POST 時に ID を指定することはしないのが一般的なので単に `POST /playlists` でよさそうです。
（https://bootcamp.fjord.jp/products/6250#comment_46545 あたりを読み返してみてください:pray:）


> Spotify というクラスを作成する予定ですが、コントローラーとしての利用だけでモデルとしては利用しない設計を考えています

なるほど、ではこのアプリは Spotify の API をいい感じに叩いてくれる、クライアントアプリであるということですね:eyes: 
上のコメントから Rails を使う予定なのかと思ったんですが、API を叩くだけで永続化したいデータがないのであれば、Rails を使う必要性がうすいような気もします。その点はどのように検討されましたでしょうか？

**Comment by ot0m1** [comment]
> POST | /search/:keyword | アーティストを検索

このアプリケーションが求めるシンプルさの表れとしてアドレスバーはなるだけすっきりさせたい、他のリソースでもパラメータは表示しないため、`POST にしつつ、検索キーワードはリクエストボディに入れて渡す`にします。

POST | /search
-- | --

に変更しました。

> POST | /playlists/:id | 新規プレイリストの追加

`:id`は、これから作成されるプレイリストの ID を想定しています。
確かに id の指定は不要でした。

POST | /playlists
-- | --

に変更しました。

> 上のコメントから Rails を使う予定なのかと思ったんですが、API を叩くだけで永続化したいデータがないのであれば、Rails を使う必要性がうすいような気もします。その点はどのように検討されましたでしょうか？

おっしゃるとおり Rails を使う予定です。
自分も Rails はこのアプリケーションの仕様に対して機能が過剰かなと思いましたが、下記の理由から Rails を採用することにしました。

- フレームワークに沿った開発経験ができる
    - フルスクラッチで書くよりフレームワークでの開発経験を積みたい
    - Sinatra などの Rails 以外の小規模なフレームワークを使うより、Rails で開発したほうが自分の資産になりそう
    - Rails のテストが書ける
- フレームワークを利用した方が CI / CD のときにも自分の資産になる経験ができそう
- フレームワークで開発しておいたほうが今後機能を追加していって規模が大きくなったときの管理が楽そう

**Comment by kfukai23** [comment]
ありがとうございます〜修正は OK です。

-----

> おっしゃるとおり Rails を使う予定です。
> 自分も Rails はこのアプリケーションの仕様に対して機能が過剰かなと思いましたが、下記の理由から Rails を採用することにしました。

正直申し上げると、今見えている情報から判断する限り、Rails を採用しても @ot0m1 さんの期待は満たされない可能性が高いように思いました（確かに「Rails の開発経験をもっと積みたい」というお気持ちはわかるのですがmm）

というのも、このアプリを Rails で作っても、資産になるような経験は得られなそうだからです。
今回作ろうとしているアプリって、Rails の特徴的な機能をほとんど使わないと思うんですね。データの永続化をしないので ActiveRecord は一切利用しないということですし、その他 Rails の構成要素となっているライブラリを使うような機能（たとえばファイルアップロードがあるなら ActiveStorage、メールを送信するなら ActionMailer など）もありません。
Rails である必然性が薄いアプリを Rails で作っても、結局上記のようなコアな機能を使わないのであれば、Rails を使ったからこその悩みやハマリポイントにはほぼ出会えません。そういった開発を経ても「自分の資産になる経験」は得られないのではないかと思います。

また、開発というのは課題に対して適切な解決手段を用いるのが基本でもあります。
もちろん、複数選択肢があるとき「使ってみたいから、学んでみたいから」という理由で決めることもあるんですが、それには選択肢のどれもが解決手段として妥当であるという前提が必要です。その前提を満たさないまま「経験を積みたいから」と採用しても、課題をうまく解決できず本末転倒になってしまうおそれがあります。
別の観点から言うと、自作サービスは追々就職活動でも名刺代わりになるので、応募先の技術者が上記のような目線で見て採用理由を聞いたら、せっかくアプリとしてのアイデアは良くてもあまり評価してもらえなくなってしまうおそれもあると思います。

今の状況をものすごく大げさに言うと、「スーパーコンピュータの利用経験を積みたいから」という理由で、電卓でもできるような四則演算にスパコンを使おうとしているような感じなんですよね（例えが適切かはわかりませんが...）。
なので、解決したい課題に対して適した手段を改めて検討していただくか、どうしても Rails を使いたいのであれば Rails が適切な手段となりうるような課題を改めて設定していただきたいです。

ちなみに、Rails を使いたいのか、それとも FW ならある程度なんでもよい（FWを使わず素の状態から作るのを避けたい）のか、どちらのほうがお気持ちに近いでしょうか？:eyes:
今回の場合はフロントエンドFW（ライブラリ）を使ってクライアントアプリを作るという方法がひとつの選択肢だと思っています。
もしお気持ち的に後者寄りなのであれば、その方針で検討するのが良さそうに思います〜。

**Comment by ot0m1** [comment]
ご指摘いただいた点非常にしっくりきました🙇‍♂️

フィヨルドブートキャンプで Ruby 及び Ruby on Rails の学習を行ってきたため、課題に対する解決手段としての採用理由より、学んだことを活かすことを重視しすぎたようです。
フィヨルドブートキャンプで Ruby 及び Ruby on Rails の学習を行ってきたから採用しないといけない、という思い込みがかなり強くありました。

> ちなみに、Rails を使いたいのか、それとも FW ならある程度なんでもよい（FWを使わず素の状態から作るのを避けたい）のか、どちらのほうがお気持ちに近いでしょうか？👀
> 今回の場合はフロントエンドFW（ライブラリ）を使ってクライアントアプリを作るという方法がひとつの選択肢だと思っています。

`FW ならある程度なんでもよい`が気持ちに近いです。

おっしゃるとおり Ruby on Rails を採用しないといけないという思い込みをなくした場合、採用技術としてはフロントエンドの
フレームワークを採用するのが非常によい選択肢であると思いました。

が、フロントエンドのフレームワークを採用すると色々抽象化してくれてしまい、ウェブアプリケーションの少し深いとことを学ぶことなくリリースできてしまうのではないか、ポートフォリオとして考えた際にフレームワーク任せな内容になってしまうのではないかという懸念点から、素の Ruby で Spotify の API 周りなどの処理を書く + ルーティング周りは Rack + Puma で自分で実装してみるという方法を採用してみたいと考えています。

**Comment by kfukai23** [comment]
おわかりいただけたようでよかったです:pray:

> ポートフォリオとして考えた際にフレームワーク任せな内容になってしまうのではないかという懸念点から

先日の「フルスクラッチで書くよりフレームワークでの開発経験を積みたい」という考えとは逆のような気がするのですが、何か考えに変化がありましたでしょうか？:eyes:

> ポートフォリオとして考えた際にフレームワーク任せな内容になってしまうのではないかという懸念点から、素の Ruby で Spotify の API 周りなどの処理を書く + ルーティング周りは Rack + Puma で自分で実装してみるという方法を採用してみたいと考えています

「ポートフォリオとして考えた際にFW任せになってしまう」というのは、ポートフォリオやその制作過程がどのように評価されるかを気にしてのことでしょうか？
だとすると、やはり「課題に対して適切な解決手段を用いる」という軸からは少し外れてしまうのが気になるところです（Rails ほど的外れではないですが）。「フロントエンドFWを使えばいいのになぜわざわざ自前実装するのか」という部分に対する評価はわりと割れそうな気がするんですよね。
現状、API をプロキシするアプリで、このくらいの規模だったら、Next.js などの FW を使って軽量に作り Netlify などのサービスでホスティングして公開する、というのが一般的かなと思います。画面をリッチに動かしたくなっても React ベースなのですぐできますしね。そういう中でそこからあえて外れることに対して、「FW に頼らず自前実装してすごい」となるか、「やりたいことに対して too much な手段を選択してしまっている」と評価されるかはちょっとわからないです（ちなみに僕は後者寄りで、もし Rails を使いたいとか技術的にやりたいことがあるなら、それに合ったサービス案を考えるのが、筋が通っていて良いんじゃないかと思うほうです）。


ちょっと @ot0m1 さんの狙いや意図するところ、お気持ちなどを僕が分かってない感じもするので、冒頭の質問にお答えいただきつつ、より詳しくお聞かせいただけると一緒に方向を考えられると思いますのでよろしくお願いします:pray:

**Comment by ot0m1** [comment]
> 先日の「フルスクラッチで書くよりフレームワークでの開発経験を積みたい」という考えとは逆のような気がするのですが、何か考えに変化がありましたでしょうか？👀

Ruby で書きたい、というのがまず強くあると自己分析しています。
むしろ Ruby で書きたいというより、フィヨルドブートキャンプで学んできたことが Ruby なので、それを使わないといけないという脅迫概念みたいになっちゃっているのかもしれません。（Ruby への愛着も別途それはそれであります）

けどプラクティスで学んできたことを振り返ると、必ずしも Ruby だけではなく Git やリソース設計、テストなど様々あって、コードを書くプラクティスのときに Ruby が指定されていただけであって、エンジニアとしてやっていくために大切なことは Ruby で何かを作るということではないなぁと思い至りました。

自作サービスのプラクティスでも、Ruby で書かなくても Git やリソース設計、デプロイ、CI/CD など学んできたことを活かせる内容ですね。

> 「ポートフォリオとして考えた際にFW任せになってしまう」というのは、ポートフォリオやその制作過程がどのように評価されるかを気にしてのことでしょうか？

その通りです。エレベーターピッチで作ったものは少なくとも自分は確実に使うし、誰かしらの課題解決もできるという自負はあるのですが、シンプルすぎるのではないかという気持ちもあります。

> 現状、API をプロキシするアプリで、このくらいの規模だったら、Next.js などの FW を使って軽量に作り Netlify などのサービスでホスティングして公開する、というのが一般的かなと思います。画面をリッチに動かしたくなっても React ベースなのですぐできますしね。そういう中でそこからあえて外れることに対して、「FW に頼らず自前実装してすごい」となるか、「やりたいことに対して too much な手段を選択してしまっている」と評価されるかはちょっとわからないです（ちなみに僕は後者寄りで、もし Rails を使いたいとか技術的にやりたいことがあるなら、それに合ったサービス案を考えるのが、筋が通っていて良いんじゃないかと思うほうです）。

ここは「やりたいことに対して too much な手段を選択してしまっている」と受け取られる @kfukai23 さんの考えの方がおそらく多数派なんだろうなと感じています。
冒頭で書いた Ruby を使わないといけないという脅迫概念で、ちょっとずれた考えになっていてもその点を冷静に見れてないかもしれません。
また、フロントエンドのフレームワークを使って素早くリリースするモダンなやり方に対して、卒業制作として楽をしてしまっているのではないかという気持ちがありました。

苦労をしないといけないのではないかという考えがあって、その思い込みから「FW に頼らず自前実装してすごい」と大多数に受け取ってもらえるのでは？となっていました。

そうなると最初に言っていた Ruby on Rails を採用するってことと矛盾するじゃんってなるのですが、その点はフィヨルドブートキャンプで学んできたことが Ruby なので、それを使わないといけないという脅迫概念から視野が狭くなっていました。

冷静になってみると、Ruby on Rails なら使っていい、それ以外のフレームワークだと楽しているという考えは全然筋が通っていないですね。

**Comment by ot0m1** [comment]
というのを書いたうえで、TypeScript + React + Next.js で作るのが良いのかなと思っています。

プラクティスでやった Vue.js ではない理由は以下です。

- Vue.js をやってみてあんまりしっくりこなかった（利点より、学習コストの方を強く感じてしまった）
- 現在勤めている会社のフロントエンドアーキテクチャ規約で、開発言語は TypeScript 、ライブラリは React 、SPA を作成する場合は Next.js を使用することが最も推奨されていること
    - 自分は転職より、現在勤めている会社でエンジニアへのジョブチェンジを優先して考えているので、フロントエンドアーキテクチャ規約で推奨されているものの経験を詰んでみたい

**Comment by kfukai23** [comment]
なるほどです、詳しく説明してくださりありがとうございます！:pray:

> 苦労をしないといけないのではないかという考えがあって、その思い込みから「FW に頼らず自前実装してすごい」と大多数に受け取ってもらえるのでは？となっていました。

サービスづくりってなにも実装だけじゃないというか、アイデア出しや設計など他にもやること色々あるんですよね。ペーパープロトタイピングやエレベーターピッチも見ましたが、そこで十分苦労されているので、実装で苦労しなかったからといってサービスづくりを楽にすませたということにはならないんじゃないかなーと思いました。
それと、ケースバイケースではありますが、楽に済むということはソリューションを適切に選んでいるということでもあると思います。そして、そういうソリューションの検討もエンジニアの腕の見せどころだったりします。なので、結果として実装が楽に済んだとしても、それ自体はなんら問題ではないと僕は考えます！

> プラクティスでやった Vue.js ではない理由は以下です。

はい、これら理由や戦略は妥当だと思いますのでその方向でよいのではないでしょうか！
やってみてしっくりこなければまた変えてもいいと思いますし。

-------

ということで、リソース設計は OK ですし気になる点もクリアになったので、合格としたいと思います〜
制作がんばってくださいね〜
